language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=1.5.12 MIGRATE='true' COLLECT='true'
  - DJANGO=1.6.11 MIGRATE='true' COLLECT='true'
  - DJANGO=1.7.11 MIGRATE='./manage.py migrate' COLLECT='true'
  - DJANGO=1.8.8 MIGRATE='./manage.py migrate' COLLECT='true'
  - DJANGO=1.9.1 MIGRATE='./manage.py migrate' COLLECT='./manage.py collectstatic --noinput --settings=chatserver.tests.settings'

sudo: true

dist: trusty

branches:
  only:
    - master

matrix:
  exclude:
    # Django 1.9 does not support python 3.3
    - env: DJANGO=1.9.1 MIGRATE='./manage.py migrate' COLLECT='./manage.py collectstatic --noinput --settings=chatserver.tests.settings'
      python: 3.3

before_install:
  - ./install-chrome-webdriver.sh

install:
  - pip install -r examples/requirements.txt
  - pip install Django==$DJANGO
  - python setup.py install

services:
  - redis-server

before_script:
  - pip freeze
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - cd examples && $MIGRATE && $COLLECT && ./manage.py test chatserver --settings=chatserver.tests.settings
