language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=1.5.12 MIGRATE='true'
  - DJANGO=1.6.11 MIGRATE='true'
  - DJANGO=1.7.7 MIGRATE='./manage.py migrate'
  - DJANGO=1.8.5 MIGRATE='./manage.py migrate'
  - DJANGO=1.9 MIGRATE='./manage.py migrate'

branches:
  only:
    - master

install:
  - pip install -q Django==$DJANGO
  - pip install -r examples/requirements.txt
  - python setup.py -q install

services:
  - redis-server

before_script:
  - pip freeze

script:
  - cd examples && $MIGRATE && ./manage.py test chatserver --settings=chatserver.tests.settings
